apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-portal
  namespace: equilibrium
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-portal
  template:
    metadata:
      labels:
        app: admin-portal
    spec:
      containers:
      - name: admin-portal
        image: equilibrium/admin-portal:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "https://api.yourdomain.com"
        - name: REACT_APP_WEBSOCKET_URL
          value: "wss://api.yourdomain.com/ws"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: admin-portal
  namespace: equilibrium
spec:
  selector:
    app: admin-portal
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
