apiVersion: apps/v1
kind: Deployment
metadata:
  name: advanced-analytics-service
  namespace: equilibrium
spec:
  replicas: 2
  selector:
    matchLabels:
      app: advanced-analytics-service
  template:
    metadata:
      labels:
        app: advanced-analytics-service
    spec:
      containers:
      - name: advanced-analytics-service
        image: equilibrium/advanced-analytics-service:latest
        ports:
        - containerPort: 8009
        env:
        - name: ADVANCED_ANALYTICS_SERVICE_PORT
          value: "8009"
        - name: MONGODB_HOST
          value: "mongodb-service"
        - name: POSTGRES_HOST
          value: "postgres-service"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8009
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8009
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: advanced-analytics-service
  namespace: equilibrium
spec:
  selector:
    app: advanced-analytics-service
  ports:
  - protocol: TCP
    port: 8009
    targetPort: 8009
  type: ClusterIP
