apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: equilibrium
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: equilibrium/auth-service:latest
        ports:
        - containerPort: 8006
        env:
        - name: AUTH_SERVICE_PORT
          value: "8006"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
        - name: POSTGRES_HOST
          value: "postgres-service"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8006
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8006
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: equilibrium
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 8006
    targetPort: 8006
  type: ClusterIP
