apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-app
  namespace: equilibrium
spec:
  replicas: 2
  selector:
    matchLabels:
      app: driver-app
  template:
    metadata:
      labels:
        app: driver-app
    spec:
      containers:
      - name: driver-app
        image: equilibrium/driver-app:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "https://api.yourdomain.com"
        - name: REACT_APP_WEBSOCKET_URL
          value: "wss://api.yourdomain.com/ws"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: driver-app
  namespace: equilibrium
spec:
  selector:
    app: driver-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
