apiVersion: apps/v1
kind: Deployment
metadata:
  name: geospatial-service
  namespace: equilibrium
spec:
  replicas: 3
  selector:
    matchLabels:
      app: geospatial-service
  template:
    metadata:
      labels:
        app: geospatial-service
    spec:
      containers:
      - name: geospatial-service
        image: equilibrium/geospatial-service:latest
        ports:
        - containerPort: 8003
        env:
        - name: GEOSPATIAL_SERVICE_PORT
          value: "8003"
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: REDIS_HOST
          value: "redis-service"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: geospatial-service
  namespace: equilibrium
spec:
  selector:
    app: geospatial-service
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8003
  type: ClusterIP
