apiVersion: apps/v1
kind: Deployment
metadata:
  name: i18n-service
  namespace: equilibrium
spec:
  replicas: 2
  selector:
    matchLabels:
      app: i18n-service
  template:
    metadata:
      labels:
        app: i18n-service
    spec:
      containers:
      - name: i18n-service
        image: equilibrium/i18n-service:latest
        ports:
        - containerPort: 8010
        env:
        - name: I18N_SERVICE_PORT
          value: "8010"
        - name: REDIS_HOST
          value: "redis-service"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: i18n-service
  namespace: equilibrium
spec:
  selector:
    app: i18n-service
  ports:
  - protocol: TCP
    port: 8010
    targetPort: 8010
  type: ClusterIP
