apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: equilibrium
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: equilibrium/notification-service:latest
        ports:
        - containerPort: 8008
        env:
        - name: NOTIFICATION_SERVICE_PORT
          value: "8008"
        - name: FCM_SERVER_KEY
          valueFrom:
            secretKeyRef:
              name: notification-secrets
              key: fcm-server-key
        - name: APNS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: notification-secrets
              key: apns-key-id
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8008
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8008
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: equilibrium
spec:
  selector:
    app: notification-service
  ports:
  - protocol: TCP
    port: 8008
    targetPort: 8008
  type: ClusterIP
