apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service
  namespace: equilibrium
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pricing-service
  template:
    metadata:
      labels:
        app: pricing-service
    spec:
      containers:
      - name: pricing-service
        image: equilibrium/pricing-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: PRICING_SERVICE_PORT
          value: "8001"
        - name: REDIS_HOST
          value: "redis-service"
        - name: POSTGRES_HOST
          value: "postgres-service"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pricing-service
  namespace: equilibrium
spec:
  selector:
    app: pricing-service
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP