apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-processor
  namespace: equilibrium
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stream-processor
  template:
    metadata:
      labels:
        app: stream-processor
    spec:
      containers:
      - name: stream-processor
        image: equilibrium/stream-processor:latest
        ports:
        - containerPort: 8004
        env:
        - name: STREAM_PROCESSOR_PORT
          value: "8004"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: REDIS_HOST
          value: "redis-service"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: stream-processor
  namespace: equilibrium
spec:
  selector:
    app: stream-processor
  ports:
  - protocol: TCP
    port: 8004
    targetPort: 8004
  type: ClusterIP
