apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
  namespace: equilibrium
spec:
  replicas: 3
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
    spec:
      containers:
      - name: websocket-service
        image: equilibrium/websocket-service:latest
        ports:
        - containerPort: 8005
        env:
        - name: WEBSOCKET_SERVICE_PORT
          value: "8005"
        - name: REDIS_HOST
          value: "redis-service"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: equilibrium
spec:
  selector:
    app: websocket-service
  ports:
  - protocol: TCP
    port: 8005
    targetPort: 8005
  type: ClusterIP
