_format_version: "3.0"
_transform: true

services:
  # Pricing Service
  - name: pricing-service
    url: http://pricing-service:8001
    routes:
      - name: pricing-routes
        strip_path: true
        paths:
          - /api/v2/pricing
          - /api/v2/estimate
          - /api/v2/surge
    plugins:
      - name: rate-limiting
        config:
          minute: 1000
          hour: 10000
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
          exposed_headers:
            - X-Auth-Token
          credentials: true
          max_age: 3600
      - name: request-transformer
        config:
          add:
            headers:
              - "X-Forwarded-For:$(headers.x-forwarded-for)"
              - "X-Real-IP:$(headers.x-real-ip)"

  # Analytics Service
  - name: analytics-service
    url: http://analytics-service:8002
    routes:
      - name: analytics-routes
        strip_path: true
        paths:
          - /api/v2/analytics
          - /api/v2/metrics
          - /api/v2/reports
    plugins:
      - name: rate-limiting
        config:
          minute: 500
          hour: 5000
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
          credentials: true
          max_age: 3600

  # Geospatial Service
  - name: geospatial-service
    url: http://geospatial-service:8003
    routes:
      - name: geospatial-routes
        strip_path: true
        paths:
          - /api/v2/geospatial
          - /api/v2/zones
          - /api/v2/location
    plugins:
      - name: rate-limiting
        config:
          minute: 2000
          hour: 20000
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
          credentials: true
          max_age: 3600

  # Stream Processor Service
  - name: stream-processor-service
    url: http://stream-processor:8004
    routes:
      - name: stream-processor-routes
        strip_path: true
        paths:
          - /api/v2/stream
          - /api/v2/events
    plugins:
      - name: rate-limiting
        config:
          minute: 1000
          hour: 10000
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
          credentials: true
          max_age: 3600

  # WebSocket Service
  - name: websocket-service
    url: http://websocket-service:8005
    routes:
      - name: websocket-routes
        strip_path: true
        paths:
          - /ws
          - /api/v2/websocket
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
            - Upgrade
            - Connection
          credentials: true
          max_age: 3600

  # Authentication Service
  - name: auth-service
    url: http://auth-service:8006
    routes:
      - name: auth-routes
        strip_path: true
        paths:
          - /api/v2/auth
          - /api/v2/login
          - /api/v2/logout
          - /api/v2/register
          - /api/v2/refresh
    plugins:
      - name: rate-limiting
        config:
          minute: 100
          hour: 1000
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
          credentials: true
          max_age: 3600

  # ML Pricing Service
  - name: ml-pricing-service
    url: http://ml-pricing-service:8007
    routes:
      - name: ml-pricing-routes
        strip_path: true
        paths:
          - /api/v2/ml
          - /api/v2/predict
          - /api/v2/model
    plugins:
      - name: rate-limiting
        config:
          minute: 500
          hour: 5000
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
          credentials: true
          max_age: 3600

  # Notification Service
  - name: notification-service
    url: http://notification-service:8008
    routes:
      - name: notification-routes
        strip_path: true
        paths:
          - /api/v2/notifications
          - /api/v2/push
    plugins:
      - name: rate-limiting
        config:
          minute: 200
          hour: 2000
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
          credentials: true
          max_age: 3600

  # i18n Service
  - name: i18n-service
    url: http://i18n-service:8009
    routes:
      - name: i18n-routes
        strip_path: true
        paths:
          - /api/v2/i18n
          - /api/v2/translate
          - /api/v2/languages
    plugins:
      - name: rate-limiting
        config:
          minute: 1000
          hour: 10000
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
          credentials: true
          max_age: 3600

  # Failure Handler Service
  - name: failure-handler-service
    url: http://failure-handler-service:8010
    routes:
      - name: failure-handler-routes
        strip_path: true
        paths:
          - /api/v2/failure
          - /api/v2/health
          - /api/v2/status
    plugins:
      - name: rate-limiting
        config:
          minute: 100
          hour: 1000
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
          credentials: true
          max_age: 3600

# Global plugins
plugins:
  - name: prometheus
    config:
      per_consumer: true
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true

  - name: correlation-id
    config:
      header_name: "Kong-Request-ID"
      echo_downstream: true
      generator: "uuid#counter"

# Consumers for API key authentication
consumers:
  - username: admin-user
    custom_id: admin-001
    keyauth_credentials:
      - key: admin-api-key-2025
  - username: mobile-app
    custom_id: mobile-001
    keyauth_credentials:
      - key: mobile-api-key-2025
  - username: driver-app
    custom_id: driver-001
    keyauth_credentials:
      - key: driver-api-key-2025
  - username: analytics-service
    custom_id: analytics-001
    keyauth_credentials:
      - key: analytics-api-key-2025

# ACL groups
acls:
  - consumer: admin-user
    group: admin
  - consumer: mobile-app
    group: mobile
  - consumer: driver-app
    group: driver
  - consumer: analytics-service
    group: service
