global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Pricing Service
  - job_name: 'pricing-service'
    static_configs:
      - targets: ['pricing-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Analytics Service
  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Geospatial Service
  - job_name: 'geospatial-service'
    static_configs:
      - targets: ['geospatial-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Stream Processor
  - job_name: 'stream-processor'
    static_configs:
      - targets: ['stream-processor:8004']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # WebSocket Service
  - job_name: 'websocket-service'
    static_configs:
      - targets: ['websocket-service:8005']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8006']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # ML Pricing Service
  - job_name: 'ml-pricing-service'
    static_configs:
      - targets: ['ml-pricing-service:8007']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Notification Service
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8008']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Advanced Analytics Service
  - job_name: 'advanced-analytics-service'
    static_configs:
      - targets: ['advanced-analytics-service:8009']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # i18n Service
  - job_name: 'i18n-service'
    static_configs:
      - targets: ['i18n-service:8010']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 15s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 15s
